/** Tags e atributos permitidos em HTML rico (posts). Partilhado entre servidor e browser. */
export const RICH_HTML_ALLOWED_TAGS = [
  "p",
  "br",
  "strong",
  "b",
  "em",
  "i",
  "u",
  "s",
  "ul",
  "ol",
  "li",
  "a",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "blockquote",
  "pre",
  "code",
  "span",
  "div",
  "img",
  "hr",
  "sub",
  "sup",
];

/** @type {Record<string, string[]>} */
export const RICH_HTML_ALLOWED_ATTRS = {
  a: ["href", "title", "target", "rel"],
  img: ["src", "alt", "title", "width", "height"],
  span: ["class"],
  div: ["class"],
  p: ["class"],
  h1: ["class"],
  h2: ["class"],
  h3: ["class"],
  h4: ["class"],
  h5: ["class"],
  h6: ["class"],
  blockquote: ["class"],
  code: ["class"],
  pre: ["class"],
};
